### ISSUE TITLE
Attempting to install

### ISSUE THREAD

**Issue by blue-santa** [matusnovak/doxybook2#1]
Hi matusnovak,

This project looks very intriguing. I use Vuepress at work and I have requests from developers on the team to integrate Doxygen, so this looks like a perfect fit.

I'm trying to install, and I keep getting this error:

```
$ cmake CMakeLists.txt 
CMake Error at CMakeLists.txt:30 (add_subdirectory):
  The source directory

    /home/siddhartha/Documents/01-Studio/03-Personal-Public/01-Exercises/05-Miscellaneous/doxybook2/libs/tinyxml2

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:31 (add_subdirectory):
  The source directory

    /home/siddhartha/Documents/01-Studio/03-Personal-Public/01-Exercises/05-Miscellaneous/doxybook2/libs/fmt

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:32 (target_include_directories):
  Cannot specify include directories for target "fmt" which is not built by
  this project.


-- Configuring incomplete, errors occurred!
See also "/home/siddhartha/Documents/01-Studio/03-Personal-Public/01-Exercises/05-Miscellaneous/doxybook2/CMakeFiles/CMakeOutput.log".
```

There are no libraries in the `libs` directory, and I'm assuming cmake would install them, if I could use it correctly.

And then in the src directory, if I try to run cmake in either the Doxybook or DoxybookCLI projects, I get errors that indicate that the libraries have not been installed, such as:

```
/doxybook2/src/DoxybookCli/main.cpp:4:10: fatal error: argagg/argagg.hpp: No such file or directory
    4 | #include <argagg/argagg.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Doxybook2Cli.dir/build.make:76: CMakeFiles/Doxybook2Cli.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/Doxybook2Cli.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I'm just learning Cmake, so I'm likely doing something wrong. Let me know what it is please. Look forward to looking over all the code!

B

**Comment by matusnovak** [comment]
Hi @siddhartha-crypto 

> There are no libraries in the libs directory

It seems you are **missing submodules**. You can install them by **going into the project root directory** and running `git submodule update --init --recursive`.  That should resolve the error  `does not contain a CMakeLists.txt file.`. If you have downloaded the project as a zip/tar file instead of doing `git clone` then the command will not work. Git clone the repository instead.

> I'm assuming cmake would install them

**CMake does not download them automatically**, you have to use the `git submodule` command.

> And then in the src directory, if I try to run cmake in either the Doxybook or DoxybookCLI projects

You have to **run the CMake command from the project root folder**. If you try to run it from a subdirectory you will get only partial configuration and most likely it will fail with errors. Follor the commands here: https://github.com/matusnovak/doxybook2#install-from-source or use a CMake GUI as **shown in the screenshot below **.

Also note that you should specify a folder where CMake should put the output files. As a general rule of thumb put it in a "build" folder. On the command line it is done by:

```
cd project-path
mkdir build
cd build
cmake -G "..." -DHELLO=WORLD .. # Notice the two dots at the end specifying the parent folder
```

Also, notice the `-DBUILD_SHARED_LIBS=OFF` and other defines in the section here: https://github.com/matusnovak/doxybook2#install-from-source . The `BUILD_SHARED_LIBS=OFF` will build a single executable file (no extra dynamic library files) and the other `-D...` turn off tests and documentation. Turn all of them off.

Configure via the GUI:

![image](https://user-images.githubusercontent.com/10331278/75073447-b7796e80-54f9-11ea-9853-b0c88ba9e9e4.png)

**Comment by blue-santa** [comment]
hey there, thank you very much.

I'm sorry, my brain is totally dead right now. The result of a newborn and no sleep for a month.

I wrote a message yesterday saying that I had misread the instructions, and I must have forgot to hit "comment."

I was able to get everything installed and running on my desktop. I think I should be okay now.

Thanks! I'll keep you posted.

**Comment by matusnovak** [comment]
No worries :D 

I am glad you got it working. I will close the issue for now. Feel free to report any bugs you will find as this is still a new project.
