### ISSUE TITLE
unneeded twice Classes in markdown link anchor

### ISSUE THREAD

**Issue by devel0** [matusnovak/doxybook2#28]
platform: Ubuntu 20.04
doxybook2 version: v1.3.0

**behavior**
in class doc file ( [example](https://github.com/devel0/iot-stepper-motor/blob/5fab0a94f1f7964064c106478f6eb40a58f0cd39/data/api/Classes/classSCurveStepper.md) ) there is a unneeded `Classes/` prefixed path that makes navigation not working. ( try to click on a function )

**expected**
no `Classes/` prefix to allow link work

**repro**

```sh
git clone https://github.com/devel0/iot-stepper-motor.git
cd iot-stepper-motor
git checkout issue-doxybook2
./build-doc.sh
```

**Comment by matusnovak** [comment]
Hi @devel0 

That's because your `baseUrl` in your config file has is empty. This tool expects you to provide some base url so that links can be properly formed.

In your particular example, if you wish to view the documentation from GitHub directly, your base url should be your output folder -> `"baseUrl": "https://github.com/devel0/iot-stepper-motor/tree/main/data/api/"`.

If you wish to view the documentation from GitHub pages, it should be: `https://iot-stepper-motor.github.com/devel0/ + <folder_path>`.

Since you have no baseUrl set, the links are relative in your web browser, so that's why you see `.../classes/classes/...`. 

I am currently working on refactoring this tool so that this problem will be solved by not requiring the baseUrl property. But it's not going to be any time soon.

**Comment by devel0** [comment]
Hi @matusnovak 

many thanks, I confirm it worked
